### ISSUE TITLE
Complete ayur.py

### ISSUE THREAD

**Issue by SiddharthSham** [sanjaytharagesh31/duckFood#2]
Nikish and Karan, complete this function for weight and length, respectively. Refer to this document  for conversion rates: [http://www.ayurveda-seminare.de/site/fileadmin/kursbilder/Part_II_Vol_II_APPENDIX_7-8.pdf](url)

**Comment by prabakaran-a-s** [comment]
Yes, I've added weight units from the APPENDIX 7.
Will update time units soon enough.
